Update post-checkout hook
Instead of using pull/id/merge , a merge commit is created manually.
Github reference is not updated in case there is a conflict and it could
cause that Buildkite runs the pipeline in an old changeset.

diff --git a/.buildkite/hooks/post-checkout b/.buildkite/hooks/post-checkout
--- a/.buildkite/hooks/post-checkout
+++ b/.buildkite/hooks/post-checkout
@@ -3,12 +3,33 @@
 set -euo pipefail
 
 checkout_merge() {
-    local pr_id=$1
-    local branch=$2
+    local target_branch=$1
+    local pr_commit=$2
+    local merge_branch=$3
 
-    echo "Checking out reference refs/pull/${pr_id}/merge into ${branch}"
-    git fetch origin +refs/pull/${pr_id}/merge:${branch}
-    git checkout ${branch}
+    if [[ -z "${target_branch}" ]]; then
+        echo "No pull request target branch"
+        exit 1
+    fi
+
+    git fetch -v origin "${target_branch}"
+    git checkout FETCH_HEAD
+    echo "Current branch: $(git rev-parse --abbrev-ref HEAD)"
+
+    # create temporal branch to merge the PR with the target branch
+    git checkout -b ${merge_branch}
+    echo "Current branch: $(git rev-parse --abbrev-ref HEAD)"
+
+    # env vars to ensure merge is non-interactive
+    GIT_AUTHOR_NAME="github-merged-pr-post-checkout" \
+    GIT_COMMITTER_EMAIL="auto-merge@buildkite" \
+    GIT_COMMITTER_NAME="github-merged-pr-post-checkout" \
+    git merge --no-edit "${BUILDKITE_COMMIT}" || {
+        local merge_result=$?
+        echo "Merge failed: ${merge_result}"
+        git merge --abort
+        exit ${merge_result}
+    }
 }
 
 pull_request="${BUILDKITE_PULL_REQUEST:-false}"
@@ -18,11 +39,12 @@ if [[ "${pull_request}" == "false" ]]; then
     exit 0
 fi
 
-# use merge changeset
+TARGET_BRANCH="${BUILDKITE_PULL_REQUEST_BASE_BRANCH:-master}"
+PR_COMMIT="${BUILDKITE_COMMIT}"
 PR_ID=${BUILDKITE_PULL_REQUEST}
 MERGE_BRANCH="pr_merge_${PR_ID}"
 
-checkout_merge ${PR_ID} ${MERGE_BRANCH}
+checkout_merge "${TARGET_BRANCH}" "${PR_COMMIT}" "${MERGE_BRANCH}"
 
 echo "Commit information"
 git log --format=%B -n 1
